In [1]:
import numpy as np


Arrays in numpy

In [3]:
arr=np.array([1,2,3,4,5]) #1d-array
arr

array([1, 2, 3, 4, 5])

In [4]:
arr2=np.array([[1,2,3],[4,5,6]])    #2D array
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,23,4]],[[24,5,67],[1,34,67]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 1, 23,  4]],

       [[24,  5, 67],
        [ 1, 34, 67]]])

### Dimension of array


In [6]:
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


### Accessing array element

In [7]:
print(arr[0])

1


In [9]:
print(arr2[0,1])

2


In [11]:
print (arr3[0,1,2])

6


### Slicing arrays

In [12]:
print (arr[1:3])   #array_name[start:end:step]

[2 3]


In [13]:
print(arr[:4])

[1 2 3 4]


In [14]:
#2d array slicing
print(arr2[1,1:4])

[5 6]


### Data types in numpy



In [15]:
print (arr.dtype)

int32


In [16]:
fruit = np.array(['apple', 'banana', 'cherry'])
print(fruit.dtype)

<U6


In [17]:
#creating array with a defined type

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


### Copy and view in numpy

In [19]:
#copy donot affects the original array
#view does 

In [20]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


### Shape of array

In [22]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


### Reshaping array

In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
